version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db:5432/urls_db
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=False
      - SECRET_KEY=secret-key
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: urls_db_container
    environment:
      POSTGRES_DB: urls_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
